[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
build_flags =
    -Wall
    -Os
    -DBMX280PIO_RP2040_STANDALONE_TEST
lib_deps =
    /home/angelo/Documentos/TwoWirePIO_RP2040
