[env:benchmark]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
build_flags = -Wall -Os -I/home/angelo/Documentos/TwoWirePIO_RP2040/src
lib_deps =
    adafruit/Adafruit BMP280 Library @ ^2.6
    adafruit/Adafruit Unified Sensor @ ^1.1
    adafruit/Adafruit BusIO @ ^1.14
lib_ldf_mode = deep
lib_extra_dirs =
    /home/angelo/Documentos/BMx280PIO_RP2040
    /home/angelo/Documentos/BMx280PIO_RP2040/lib
