// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// i2c_master //
// ---------- //

#define i2c_master_wrap_target 0
#define i2c_master_wrap 31
#define i2c_master_pio_version 0

static const uint16_t i2c_master_program_instructions[] = {
            //     .wrap_target
    0x98a0, //  0: pull   block           side 1
    0x7881, //  1: out    pindirs, 1      side 1
    0x7041, //  2: out    y, 1            side 0
    0x106c, //  3: jmp    !y, 12          side 0
    0x7081, //  4: out    pindirs, 1      side 0
    0xf027, //  5: set    x, 7            side 0
    0xb942, //  6: nop                    side 1 [1]
    0x5801, //  7: in     pins, 1         side 1
    0xb142, //  8: nop                    side 0 [1]
    0xb142, //  9: nop                    side 0 [1]
    0x1046, // 10: jmp    x--, 6          side 0
    0x1019, // 11: jmp    25              side 0
    0xf027, // 12: set    x, 7            side 0
    0x7181, // 13: out    pindirs, 1      side 0 [1]
    0xb942, // 14: nop                    side 1 [1]
    0xb942, // 15: nop                    side 1 [1]
    0xb142, // 16: nop                    side 0 [1]
    0xb142, // 17: nop                    side 0 [1]
    0x104d, // 18: jmp    x--, 13         side 0
    0x7181, // 19: out    pindirs, 1      side 0 [1]
    0xb942, // 20: nop                    side 1 [1]
    0xb942, // 21: nop                    side 1 [1]
    0x5801, // 22: in     pins, 1         side 1
    0xb142, // 23: nop                    side 0 [1]
    0x9000, // 24: push   noblock         side 0
    0x7041, // 25: out    y, 1            side 0
    0x107f, // 26: jmp    !y, 31          side 0
    0xf181, // 27: set    pindirs, 1      side 0 [1]
    0xb942, // 28: nop                    side 1 [1]
    0xb942, // 29: nop                    side 1 [1]
    0xf981, // 30: set    pindirs, 1      side 1 [1]
    0xd800, // 31: irq    nowait 0        side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program i2c_master_program = {
    .instructions = i2c_master_program_instructions,
    .length = 32,
    .origin = -1,
    .pio_version = i2c_master_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config i2c_master_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + i2c_master_wrap_target, offset + i2c_master_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

