// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// i2c_burst //
// --------- //

#define i2c_burst_wrap_target 0
#define i2c_burst_wrap 31
#define i2c_burst_pio_version 0

static const uint16_t i2c_burst_program_instructions[] = {
            //     .wrap_target
    0x98a0, //  0: pull   block           side 1
    0x7841, //  1: out    y, 1            side 1
    0x1865, //  2: jmp    !y, 5           side 1
    0xf881, //  3: set    pindirs, 1      side 1
    0x1106, //  4: jmp    6               side 0 [1]
    0x1006, //  5: jmp    6               side 0
    0x7041, //  6: out    y, 1            side 0
    0x7021, //  7: out    x, 1            side 0
    0x1075, //  8: jmp    !y, 21          side 0
    0xf080, //  9: set    pindirs, 0      side 0
    0xf047, // 10: set    y, 7            side 0
    0xbb42, // 11: nop                    side 1 [3]
    0x5801, // 12: in     pins, 1         side 1
    0xb342, // 13: nop                    side 0 [3]
    0x108b, // 14: jmp    y--, 11         side 0
    0x1033, // 15: jmp    !x, 19          side 0
    0xf181, // 16: set    pindirs, 1      side 0 [1]
    0xbb42, // 17: nop                    side 1 [3]
    0xfb80, // 18: set    pindirs, 0      side 1 [3]
    0x9000, // 19: push   noblock         side 0
    0xd800, // 20: irq    nowait 0        side 1
    0xb041, // 21: mov    y, x            side 0
    0xf027, // 22: set    x, 7            side 0
    0x7181, // 23: out    pindirs, 1      side 0 [1]
    0xbb42, // 24: nop                    side 1 [3]
    0xb342, // 25: nop                    side 0 [3]
    0x1057, // 26: jmp    x--, 23         side 0
    0x107f, // 27: jmp    !y, 31          side 0
    0xf181, // 28: set    pindirs, 1      side 0 [1]
    0xbb42, // 29: nop                    side 1 [3]
    0xfb80, // 30: set    pindirs, 0      side 1 [3]
    0xd800, // 31: irq    nowait 0        side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program i2c_burst_program = {
    .instructions = i2c_burst_program_instructions,
    .length = 32,
    .origin = -1,
    .pio_version = i2c_burst_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config i2c_burst_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + i2c_burst_wrap_target, offset + i2c_burst_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

