// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------- //
// test_push_only //
// -------------- //

#define test_push_only_wrap_target 0
#define test_push_only_wrap 2
#define test_push_only_pio_version 0

static const uint16_t test_push_only_program_instructions[] = {
            //     .wrap_target
    0xe027, //  0: set    x, 7
    0xa0c1, //  1: mov    isr, x
    0x8000, //  2: push   noblock
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program test_push_only_program = {
    .instructions = test_push_only_program_instructions,
    .length = 3,
    .origin = -1,
    .pio_version = test_push_only_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config test_push_only_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + test_push_only_wrap_target, offset + test_push_only_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

